# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zaxui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zaxui(object):
    def setupUi(self, zaxui):
        zaxui.setObjectName("zaxui")
        zaxui.resize(1543, 889)
        self.centralwidget = QtWidgets.QWidget(zaxui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-320, -130, 1871, 971))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("material/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 690, 371, 281))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("material/B.G_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, -150, 1161, 821))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("material/Aqua.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 240, 231, 91))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"background-image:url(:/newPrefix/s1.png);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1270, 250, 221, 71))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"background-image:url(:/newPrefix/q1.png);\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.terminalOutputBox.setGeometry(QtCore.QRect(0, 560, 1551, 331))
        self.terminalOutputBox.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"}")
        self.terminalOutputBox.setObjectName("terminalOutputBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 130, 341, 311))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("material/sameer-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.terminalOutputBox.raise_()
        self.label_4.raise_()
        zaxui.setCentralWidget(self.centralwidget)

        self.retranslateUi(zaxui)
        QtCore.QMetaObject.connectSlotsByName(zaxui)

    def retranslateUi(self, zaxui):
        _translate = QtCore.QCoreApplication.translate
        zaxui.setWindowTitle(_translate("zaxui", "MainWindow"))
        self.terminalOutputBox.setPlainText(_translate("zaxui", "bvcxcbx\n"
""))
import rec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zaxui = QtWidgets.QMainWindow()
    ui = Ui_zaxui()
    ui.setupUi(zaxui)
    zaxui.show()
    sys.exit(app.exec_())
